Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,3 +1,4 @@
+
 name: checkov-check
 
 on:
@@ -5,11 +6,13 @@ on:
     branches:
       - 'tech-dev-*'
 
-permissions: read-all
+permissions: 
+  contents: read
 
 jobs:
   checkov-check:
     runs-on: ubuntu-latest
+
     steps:
       - name: Install dependencies
         run: |
@@ -38,3 +41,12 @@ jobs:
             exit 1
           fi
 
+      - name: Terraform Apply
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        run: |
+          echo "Applying Terraform changes..."
+          terraform apply -auto-approve plan.out
+          if [ $? -ne 0 ]; then
+            echo "Terraform Apply failed"
+            exit 1
+          fi
